#!/usr/bin/env python3
"""Turn the NXE logotype into femtovg path commands.

**The SVG is the source; the Rust is generated.** femtovg has no SVG reader, and
pulling one in to draw one shape would cost a dependency and a licence for
geometry that never changes. Run `mise run logo:generate` after editing the SVG.

The colour in the file is ignored on purpose: the mark is painted with whatever
token the window is using, so it inverts with the surface like everything else
(`crates/nxe-ui/src/theme.rs`).
"""

import re
from pathlib import Path

SVG = Path("crates/nxe-ui/assets/nxe/logo.svg")
OUT = Path("crates/nxe-ui/src/logo/generated.rs")

NUMBER = re.compile(r"-?\d*\.?\d+(?:e-?\d+)?")


def rust(value):
    """A float literal clippy will accept.

    **Trailing zeros are an error here**, not a style: `excessive_precision`
    fires on `182.0000` because an `f32` cannot hold what the digits promise.
    One decimal always stays, or the literal becomes an integer and stops
    type-checking.
    """
    text = f"{value:.4f}".rstrip("0")
    return text + "0" if text.endswith(".") else text


def numbers(text):
    return [float(n) for n in NUMBER.findall(text)]


def segments(d):
    """Absolute `M` / `L` / `H` / `V` / `C` / `Z` only — what this file uses."""
    out = []
    x = y = 0.0
    for command, body in re.findall(r"([MLHVCZ])([^MLHVCZ]*)", d, re.IGNORECASE):
        if command in "Zz":
            out.append("Close")
            continue
        values = numbers(body)
        if command == "M":
            for i in range(0, len(values), 2):
                x, y = values[i], values[i + 1]
                out.append(f"Move({rust(x)}, {rust(y)})" if i == 0 else f"Line({rust(x)}, {rust(y)})")
        elif command == "L":
            for i in range(0, len(values), 2):
                x, y = values[i], values[i + 1]
                out.append(f"Line({rust(x)}, {rust(y)})")
        elif command == "H":
            for value in values:
                x = value
                out.append(f"Line({rust(x)}, {rust(y)})")
        elif command == "V":
            for value in values:
                y = value
                out.append(f"Line({rust(x)}, {rust(y)})")
        elif command == "C":
            for i in range(0, len(values), 6):
                c = values[i : i + 6]
                x, y = c[4], c[5]
                out.append("Cubic({})".format(", ".join(rust(v) for v in c)))
        else:
            raise SystemExit(f"unhandled command {command!r}")
    return out


def main():
    svg = SVG.read_text()
    width, height = (float(v) for v in re.search(r'viewBox="0 0 ([\d.]+) ([\d.]+)"', svg).groups())
    paths = re.findall(r'<path d="([^"]+)"', svg)
    if not paths:
        raise SystemExit("no paths in the svg")

    lines = [
        "//! The NXE logotype as path commands. **Generated by",
        "//! `scripts/generate-logo.py` — do not edit.** Regenerate with",
        "//! `mise run logo:generate`.",
        "//!",
        "//! Coordinates are in the SVG's own viewbox; [`super::draw`] scales them.",
        "",
        "use super::Segment::{self, Close, Cubic, Line, Move};",
        "",
        f"/// The viewbox the coordinates below are in: {width:.0f} x {height:.0f}.",
        f"pub const VIEWBOX: (f32, f32) = ({width:.1f}, {height:.1f});",
        "",
        "pub const SEGMENTS: &[Segment] = &[",
    ]
    for path in paths:
        for segment in segments(path):
            lines.append(f"    {segment},")
    lines.append("];")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"{OUT}: {sum(len(segments(p)) for p in paths)} segments")


if __name__ == "__main__":
    main()
