#!/usr/bin/env python3
"""Regenerates nxe-ui's Lucide icon constants.

The input is Lucide's own `font/info.json`, which maps every icon name to the
codepoint it occupies in `lucide.ttf`. Both files come from the `lucide-static`
npm package and live beside each other in `crates/nxe-ui/assets/lucide/`.

To update Lucide:

    curl -o crates/nxe-ui/assets/lucide/lucide.ttf \
        https://cdn.jsdelivr.net/npm/lucide-static@<version>/font/lucide.ttf
    curl -o crates/nxe-ui/assets/lucide/info.json \
        https://cdn.jsdelivr.net/npm/lucide-static@<version>/font/info.json
    mise run icons:generate

The font and the constants have to be updated together: a codepoint that moved
would otherwise render as a different icon, silently.
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
INFO = ROOT / "crates/nxe-ui/assets/lucide/info.json"
OUT = ROOT / "crates/nxe-ui/src/icon/generated.rs"

HEADER = """//! Lucide codepoints. **Generated by `scripts/generate-icons.py` — do not
//! edit.** Regenerate with `mise run icons:generate`.
//!
//! One constant per icon, named after the icon. The strings are single
//! characters in the private use area, which only mean anything in the `lucide`
//! font family (`nxe_ui::icon::FAMILY`).
"""


def main() -> None:
    icons = json.loads(INFO.read_text())
    lines = [HEADER]

    for name in sorted(icons):
        codepoint = icons[name]["encodedCode"].lstrip("\\")
        identifier = name.upper().replace("-", "_")
        lines.append(f'pub const {identifier}: &str = "\\u{{{codepoint}}}";')

    OUT.write_text("\n".join(lines) + "\n")
    print(f"{OUT.relative_to(ROOT)}: {len(icons)} icons")


if __name__ == "__main__":
    main()
